### ISSUE TITLE
Software Availability

### ISSUE THREAD

**Issue by TheLostLambda** [csbl/platereader#3]
Hello!
I've just read the paper describing this device in The Journal of Laboratory Automation which linked me here for the software for both the reader and database servers.

Alas, I cannot find any of the software here. Where should I look?

**Comment by BonnieDougherty** [comment]
The schematics for building a reader are located at https://github.com/csbl/platereader and the code is located in a separate repository at https://github.com/csbl/PlateReaderCode.
